export const TYPES = {
    REQUEST_PERMISSION_START:'pfm.AUTH.REQUEST_PERMISSION_START',
    REQUEST_PERMISSION_SUCCESS: 'pfm.AUTH.REQUEST_PERMISSION_SUCCESS',
    REQUEST_PERMISSION_FAILED: 'pfm.AUTH.REQUEST_PERMISSION_FAILED',
    USER_CANCELLED_LOGIN: 'pfm.AUTH.USER_CANCELLED_LOGIN',
    SERVER_AUTH_SUCCESS: 'pfm.AUTH.SERVER_AUTH_SUCCESS',
    SERVER_AUTH_FAILED: 'pfm.AUTH.SERVER_AUTH_FAILED',
}